FROM ubuntu:22.04


ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get install -y git gedit fish

RUN apt-get install -y python3-pip

RUN pip3 install opencv-python

RUN apt install libxcb-xinerama0

RUN pip3 install sympy
RUN pip3 install scipy

CMD ["fish"]
